spring.application.name=demo
server.port=7777

# Server configuration
#server.port=8080

# Actuator configuration
management.endpoints.web.exposure.include=health,info,metrics,custom
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.endpoints.web.base-path=/actuator
management.endpoints.enabled-by-default=true

# Enable custom endpoints
management.endpoint.custom.enabled=true

# Add custom info
info.app.name=Simple Actuator Demo
info.app.description=A simple Spring Boot application with Actuator
info.app.version=1.0.0
info.java.version=${java.version}